
package RM1.dams.SHEServerGenerated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SHEHospitalServerService", targetNamespace = "http://server.dams.RM1/", wsdlLocation = "file:/C:/Users/mauli/Desktop/MACS/COMP%206231%20-%20Distributed%20System%20Design/Assignments/COMP%206231%20-%20DAMS%20Project/src/RM1/dams/server/SherbrookeWSDL.wsdl")
public class SHEHospitalServerService
    extends Service
{

    private final static URL SHEHOSPITALSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHEHOSPITALSERVERSERVICE_EXCEPTION;
    private final static QName SHEHOSPITALSERVERSERVICE_QNAME = new QName("http://server.dams.RM1/", "SHEHospitalServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/mauli/Desktop/MACS/COMP%206231%20-%20Distributed%20System%20Design/Assignments/COMP%206231%20-%20DAMS%20Project/src/RM1/dams/server/SherbrookeWSDL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHEHOSPITALSERVERSERVICE_WSDL_LOCATION = url;
        SHEHOSPITALSERVERSERVICE_EXCEPTION = e;
    }

    public SHEHospitalServerService() {
        super(__getWsdlLocation(), SHEHOSPITALSERVERSERVICE_QNAME);
    }

    public SHEHospitalServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHEHOSPITALSERVERSERVICE_QNAME, features);
    }

    public SHEHospitalServerService(URL wsdlLocation) {
        super(wsdlLocation, SHEHOSPITALSERVERSERVICE_QNAME);
    }

    public SHEHospitalServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHEHOSPITALSERVERSERVICE_QNAME, features);
    }

    public SHEHospitalServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SHEHospitalServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SHEHospitalServer
     */
    @WebEndpoint(name = "SHEHospitalServerPort")
    public SHEHospitalServer getSHEHospitalServerPort() {
        return super.getPort(new QName("http://server.dams.RM1/", "SHEHospitalServerPort"), SHEHospitalServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SHEHospitalServer
     */
    @WebEndpoint(name = "SHEHospitalServerPort")
    public SHEHospitalServer getSHEHospitalServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.dams.RM1/", "SHEHospitalServerPort"), SHEHospitalServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHEHOSPITALSERVERSERVICE_EXCEPTION!= null) {
            throw SHEHOSPITALSERVERSERVICE_EXCEPTION;
        }
        return SHEHOSPITALSERVERSERVICE_WSDL_LOCATION;
    }

}
