
package RM1.dams.SHEServerGenerated;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import RM1.dams.model.AppointmentType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SHEHospitalServer", targetNamespace = "http://server.dams.RM1/")
public interface SHEHospitalServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sharebrookeAppointmentScheduleOfPatientId", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SharebrookeAppointmentScheduleOfPatientId")
    @ResponseWrapper(localName = "sharebrookeAppointmentScheduleOfPatientIdResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SharebrookeAppointmentScheduleOfPatientIdResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/sharebrookeAppointmentScheduleOfPatientIdRequest", output = "http://server.dams.RM1/SHEHospitalServer/sharebrookeAppointmentScheduleOfPatientIdResponse")
    public String sharebrookeAppointmentScheduleOfPatientId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sherbrookeCancelAppointmentOfPatientId", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SherbrookeCancelAppointmentOfPatientId")
    @ResponseWrapper(localName = "sherbrookeCancelAppointmentOfPatientIdResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SherbrookeCancelAppointmentOfPatientIdResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/sherbrookeCancelAppointmentOfPatientIdRequest", output = "http://server.dams.RM1/SHEHospitalServer/sherbrookeCancelAppointmentOfPatientIdResponse")
    public String sherbrookeCancelAppointmentOfPatientId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sherbrookeListAppointmenOfType", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SherbrookeListAppointmenOfType")
    @ResponseWrapper(localName = "sherbrookeListAppointmenOfTypeResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SherbrookeListAppointmenOfTypeResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/sherbrookeListAppointmenOfTypeRequest", output = "http://server.dams.RM1/SHEHospitalServer/sherbrookeListAppointmenOfTypeResponse")
    public String sherbrookeListAppointmenOfType(
        @WebParam(name = "arg0", targetNamespace = "")
        AppointmentType arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sherbrookeBookAppointment", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SherbrookeBookAppointment")
    @ResponseWrapper(localName = "sherbrookeBookAppointmentResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SherbrookeBookAppointmentResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/sherbrookeBookAppointmentRequest", output = "http://server.dams.RM1/SHEHospitalServer/sherbrookeBookAppointmentResponse")
    public String sherbrookeBookAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        AppointmentType arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeAppointmentSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.RemoveAppointmentSHE")
    @ResponseWrapper(localName = "removeAppointmentSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.RemoveAppointmentSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/removeAppointmentSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/removeAppointmentSHEResponse")
    public String removeAppointmentSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AppointmentType arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addRecordIntoLogFileSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.AddRecordIntoLogFileSHE")
    @ResponseWrapper(localName = "addRecordIntoLogFileSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.AddRecordIntoLogFileSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/addRecordIntoLogFileSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/addRecordIntoLogFileSHEResponse")
    public void addRecordIntoLogFileSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointmentAvailabilitySHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.ListAppointmentAvailabilitySHE")
    @ResponseWrapper(localName = "listAppointmentAvailabilitySHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.ListAppointmentAvailabilitySHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/listAppointmentAvailabilitySHERequest", output = "http://server.dams.RM1/SHEHospitalServer/listAppointmentAvailabilitySHEResponse")
    public String listAppointmentAvailabilitySHE(
        @WebParam(name = "arg0", targetNamespace = "")
        AppointmentType arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppointmentScheduleSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.GetAppointmentScheduleSHE")
    @ResponseWrapper(localName = "getAppointmentScheduleSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.GetAppointmentScheduleSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/getAppointmentScheduleSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/getAppointmentScheduleSHEResponse")
    public String getAppointmentScheduleSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookAppointmentSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.BookAppointmentSHE")
    @ResponseWrapper(localName = "bookAppointmentSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.BookAppointmentSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/bookAppointmentSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/bookAppointmentSHEResponse")
    public String bookAppointmentSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        AppointmentType arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAppointmentSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.AddAppointmentSHE")
    @ResponseWrapper(localName = "addAppointmentSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.AddAppointmentSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/addAppointmentSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/addAppointmentSHEResponse")
    public String addAppointmentSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AppointmentType arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelAppointmentSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.CancelAppointmentSHE")
    @ResponseWrapper(localName = "cancelAppointmentSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.CancelAppointmentSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/cancelAppointmentSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/cancelAppointmentSHEResponse")
    public String cancelAppointmentSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "swapAppointmentSHE", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SwapAppointmentSHE")
    @ResponseWrapper(localName = "swapAppointmentSHEResponse", targetNamespace = "http://server.dams.RM1/", className = "rm1.dams.server.SwapAppointmentSHEResponse")
    @Action(input = "http://server.dams.RM1/SHEHospitalServer/swapAppointmentSHERequest", output = "http://server.dams.RM1/SHEHospitalServer/swapAppointmentSHEResponse")
    public String swapAppointmentSHE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        AppointmentType arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        AppointmentType arg4);

}
