
package RM1.dams.MTLServerGenerated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTLHospitalServerService", targetNamespace = "http://server.dams.RM1/", wsdlLocation = "file:/C:/Users/mauli/Desktop/MACS/COMP%206231%20-%20Distributed%20System%20Design/Assignments/COMP%206231%20-%20DAMS%20Project/src/RM1/dams/server/MontrealWSDL.wsdl")
public class MTLHospitalServerService
    extends Service
{

    private final static URL MTLHOSPITALSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTLHOSPITALSERVERSERVICE_EXCEPTION;
    private final static QName MTLHOSPITALSERVERSERVICE_QNAME = new QName("http://server.dams.RM1/", "MTLHospitalServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/mauli/Desktop/MACS/COMP%206231%20-%20Distributed%20System%20Design/Assignments/COMP%206231%20-%20DAMS%20Project/src/RM1/dams/server/MontrealWSDL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTLHOSPITALSERVERSERVICE_WSDL_LOCATION = url;
        MTLHOSPITALSERVERSERVICE_EXCEPTION = e;
    }

    public MTLHospitalServerService() {
        super(__getWsdlLocation(), MTLHOSPITALSERVERSERVICE_QNAME);
    }

    public MTLHospitalServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTLHOSPITALSERVERSERVICE_QNAME, features);
    }

    public MTLHospitalServerService(URL wsdlLocation) {
        super(wsdlLocation, MTLHOSPITALSERVERSERVICE_QNAME);
    }

    public MTLHospitalServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTLHOSPITALSERVERSERVICE_QNAME, features);
    }

    public MTLHospitalServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTLHospitalServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MTLHospitalServer
     */
    @WebEndpoint(name = "MTLHospitalServerPort")
    public MTLHospitalServer getMTLHospitalServerPort() {
        return super.getPort(new QName("http://server.dams.RM1/", "MTLHospitalServerPort"), MTLHospitalServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTLHospitalServer
     */
    @WebEndpoint(name = "MTLHospitalServerPort")
    public MTLHospitalServer getMTLHospitalServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.dams.RM1/", "MTLHospitalServerPort"), MTLHospitalServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTLHOSPITALSERVERSERVICE_EXCEPTION!= null) {
            throw MTLHOSPITALSERVERSERVICE_EXCEPTION;
        }
        return MTLHOSPITALSERVERSERVICE_WSDL_LOCATION;
    }

}
