package FrontEnd.server;


/**
* server/FEMethodInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndMethod.idl
* Saturday, 9 April, 2022 5:09:54 PM EDT
*/

abstract public class FEMethodInterfaceHelper
{
  private static String  _id = "IDL:server/FEMethodInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEnd.server.FEMethodInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEnd.server.FEMethodInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FrontEnd.server.FEMethodInterfaceHelper.id (), "FEMethodInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEnd.server.FEMethodInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FEMethodInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEnd.server.FEMethodInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FrontEnd.server.FEMethodInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEnd.server.FEMethodInterface)
      return (FrontEnd.server.FEMethodInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEnd.server._FEMethodInterfaceStub stub = new FrontEnd.server._FEMethodInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FrontEnd.server.FEMethodInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEnd.server.FEMethodInterface)
      return (FrontEnd.server.FEMethodInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEnd.server._FEMethodInterfaceStub stub = new FrontEnd.server._FEMethodInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
