package FrontEnd.server;

/**
* server/FEMethodInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndMethod.idl
* Saturday, 9 April, 2022 5:09:54 PM EDT
*/

public final class FEMethodInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEnd.server.FEMethodInterface value = null;

  public FEMethodInterfaceHolder ()
  {
  }

  public FEMethodInterfaceHolder (FrontEnd.server.FEMethodInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEnd.server.FEMethodInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEnd.server.FEMethodInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEnd.server.FEMethodInterfaceHelper.type ();
  }

}
