
package RM3.Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTLHealthCareImplService", targetNamespace = "http://Montreal.Server/", wsdlLocation = "file:/home/mansi/Desktop/assignment3/src/Server/Montreal/MTLServer.wsdl")
public class MTLHealthCareImplService
    extends Service
{

    private final static URL MTLHEALTHCAREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTLHEALTHCAREIMPLSERVICE_EXCEPTION;
    private final static QName MTLHEALTHCAREIMPLSERVICE_QNAME = new QName("http://Montreal.Server/", "MTLHealthCareImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/mansi/Desktop/assignment3/src/Server/Montreal/MTLServer.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTLHEALTHCAREIMPLSERVICE_WSDL_LOCATION = url;
        MTLHEALTHCAREIMPLSERVICE_EXCEPTION = e;
    }

    public MTLHealthCareImplService() {
        super(__getWsdlLocation(), MTLHEALTHCAREIMPLSERVICE_QNAME);
    }

    public MTLHealthCareImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTLHEALTHCAREIMPLSERVICE_QNAME, features);
    }

    public MTLHealthCareImplService(URL wsdlLocation) {
        super(wsdlLocation, MTLHEALTHCAREIMPLSERVICE_QNAME);
    }

    public MTLHealthCareImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTLHEALTHCAREIMPLSERVICE_QNAME, features);
    }

    public MTLHealthCareImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTLHealthCareImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MTLHealthCareImpl
     */
    @WebEndpoint(name = "MTLHealthCareImplPort")
    public MTLHealthCareImpl getMTLHealthCareImplPort() {
        return super.getPort(new QName("http://Montreal.Server/", "MTLHealthCareImplPort"), MTLHealthCareImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTLHealthCareImpl
     */
    @WebEndpoint(name = "MTLHealthCareImplPort")
    public MTLHealthCareImpl getMTLHealthCareImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Montreal.Server/", "MTLHealthCareImplPort"), MTLHealthCareImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTLHEALTHCAREIMPLSERVICE_EXCEPTION!= null) {
            throw MTLHEALTHCAREIMPLSERVICE_EXCEPTION;
        }
        return MTLHEALTHCAREIMPLSERVICE_WSDL_LOCATION;
    }

}
