
package RM3.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTLHealthCareImpl", targetNamespace = "http://Montreal.Server/")
public interface MTLHealthCareImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAppointment", targetNamespace = "http://Montreal.Server/", className = "server.montreal.AddAppointment")
    @ResponseWrapper(localName = "addAppointmentResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.AddAppointmentResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/addAppointmentRequest", output = "http://Montreal.Server/MTLHealthCareImpl/addAppointmentResponse")
    public String addAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingSchedule", targetNamespace = "http://Montreal.Server/", className = "server.montreal.GetBookingSchedule")
    @ResponseWrapper(localName = "getBookingScheduleResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.GetBookingScheduleResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/getBookingScheduleRequest", output = "http://Montreal.Server/MTLHealthCareImpl/getBookingScheduleResponse")
    public String getBookingSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "swapAppointmet", targetNamespace = "http://Montreal.Server/", className = "server.montreal.SwapEvent")
    @ResponseWrapper(localName = "swapEventResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.SwapEventResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/swapEventRequest", output = "http://Montreal.Server/MTLHealthCareImpl/swapEventResponse")
    public String swapAppointmet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewCustomerToClients", targetNamespace = "http://Montreal.Server/", className = "server.montreal.AddNewCustomerToClients")
    @ResponseWrapper(localName = "addNewCustomerToClientsResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.AddNewCustomerToClientsResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/addNewCustomerToClientsRequest", output = "http://Montreal.Server/MTLHealthCareImpl/addNewCustomerToClientsResponse")
    public void addNewCustomerToClients(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeAppointment", targetNamespace = "http://Montreal.Server/", className = "server.montreal.RemoveAppointment")
    @ResponseWrapper(localName = "removeAppointmentResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.RemoveAppointmentResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/removeAppointmentRequest", output = "http://Montreal.Server/MTLHealthCareImpl/removeAppointmentResponse")
    public String removeAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointmentAvailability", targetNamespace = "http://Montreal.Server/", className = "server.montreal.ListAppointmentAvailability")
    @ResponseWrapper(localName = "listAppointmentAvailabilityResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.ListAppointmentAvailabilityResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/listAppointmentAvailabilityRequest", output = "http://Montreal.Server/MTLHealthCareImpl/listAppointmentAvailabilityResponse")
    public String listAppointmentAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookAppointment", targetNamespace = "http://Montreal.Server/", className = "server.montreal.BookAppointment")
    @ResponseWrapper(localName = "bookAppointmentResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.BookAppointmentResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/bookAppointmentRequest", output = "http://Montreal.Server/MTLHealthCareImpl/bookAppointmentResponse")
    public String bookAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelAppointment", targetNamespace = "http://Montreal.Server/", className = "server.montreal.CancelAppointment")
    @ResponseWrapper(localName = "cancelAppointmentResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.CancelAppointmentResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/cancelAppointmentRequest", output = "http://Montreal.Server/MTLHealthCareImpl/cancelAppointmentResponse")
    public String cancelAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeEventUDP", targetNamespace = "http://Montreal.Server/", className = "server.montreal.RemoveEventUDP")
    @ResponseWrapper(localName = "removeEventUDPResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.RemoveEventUDPResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/removeEventUDPRequest", output = "http://Montreal.Server/MTLHealthCareImpl/removeEventUDPResponse")
    public String removeEventUDP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointmentAvailabilityUDP", targetNamespace = "http://Montreal.Server/", className = "server.montreal.ListAppointmentAvailabilityUDP")
    @ResponseWrapper(localName = "listAppointmentAvailabilityUDPResponse", targetNamespace = "http://Montreal.Server/", className = "server.montreal.ListAppointmentAvailabilityUDPResponse")
    @Action(input = "http://Montreal.Server/MTLHealthCareImpl/listAppointmentAvailabilityUDPRequest", output = "http://Montreal.Server/MTLHealthCareImpl/listAppointmentAvailabilityUDPResponse")
    public String listAppointmentAvailabilityUDP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
