
package RM3.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QUEHealthCareImpl", targetNamespace = "http://Quebec.Server/")
public interface QUEHealthCareImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAppointment", targetNamespace = "http://Quebec.Server/", className = "server.quebec.AddAppointment")
    @ResponseWrapper(localName = "addAppointmentResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.AddAppointmentResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/addAppointmentRequest", output = "http://Quebec.Server/QUEHealthCareImpl/addAppointmentResponse")
    public String addAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingSchedule", targetNamespace = "http://Quebec.Server/", className = "server.quebec.GetBookingSchedule")
    @ResponseWrapper(localName = "getBookingScheduleResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.GetBookingScheduleResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/getBookingScheduleRequest", output = "http://Quebec.Server/QUEHealthCareImpl/getBookingScheduleResponse")
    public String getBookingSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "swapAppointmet", targetNamespace = "http://Quebec.Server/", className = "server.quebec.SwapEvent")
    @ResponseWrapper(localName = "swapEventResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.SwapEventResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/swapEventRequest", output = "http://Quebec.Server/QUEHealthCareImpl/swapEventResponse")
    public String swapAppointmet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewCustomerToClients", targetNamespace = "http://Quebec.Server/", className = "server.quebec.AddNewCustomerToClients")
    @ResponseWrapper(localName = "addNewCustomerToClientsResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.AddNewCustomerToClientsResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/addNewCustomerToClientsRequest", output = "http://Quebec.Server/QUEHealthCareImpl/addNewCustomerToClientsResponse")
    public void addNewCustomerToClients(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeAppointment", targetNamespace = "http://Quebec.Server/", className = "server.quebec.RemoveAppointment")
    @ResponseWrapper(localName = "removeAppointmentResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.RemoveAppointmentResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/removeAppointmentRequest", output = "http://Quebec.Server/QUEHealthCareImpl/removeAppointmentResponse")
    public String removeAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointmentAvailability", targetNamespace = "http://Quebec.Server/", className = "server.quebec.ListAppointmentAvailability")
    @ResponseWrapper(localName = "listAppointmentAvailabilityResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.ListAppointmentAvailabilityResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/listAppointmentAvailabilityRequest", output = "http://Quebec.Server/QUEHealthCareImpl/listAppointmentAvailabilityResponse")
    public String listAppointmentAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookAppointment", targetNamespace = "http://Quebec.Server/", className = "server.quebec.BookAppointment")
    @ResponseWrapper(localName = "bookAppointmentResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.BookAppointmentResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/bookAppointmentRequest", output = "http://Quebec.Server/QUEHealthCareImpl/bookAppointmentResponse")
    public String bookAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelAppointment", targetNamespace = "http://Quebec.Server/", className = "server.quebec.CancelAppointment")
    @ResponseWrapper(localName = "cancelAppointmentResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.CancelAppointmentResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/cancelAppointmentRequest", output = "http://Quebec.Server/QUEHealthCareImpl/cancelAppointmentResponse")
    public String cancelAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeEventUDP", targetNamespace = "http://Quebec.Server/", className = "server.quebec.RemoveEventUDP")
    @ResponseWrapper(localName = "removeEventUDPResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.RemoveEventUDPResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/removeEventUDPRequest", output = "http://Quebec.Server/QUEHealthCareImpl/removeEventUDPResponse")
    public String removeEventUDP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointmentAvailabilityUDP", targetNamespace = "http://Quebec.Server/", className = "server.quebec.ListAppointmentAvailabilityUDP")
    @ResponseWrapper(localName = "listAppointmentAvailabilityUDPResponse", targetNamespace = "http://Quebec.Server/", className = "server.quebec.ListAppointmentAvailabilityUDPResponse")
    @Action(input = "http://Quebec.Server/QUEHealthCareImpl/listAppointmentAvailabilityUDPRequest", output = "http://Quebec.Server/QUEHealthCareImpl/listAppointmentAvailabilityUDPResponse")
    public String listAppointmentAvailabilityUDP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
