
package RM3.SHEServerGenerated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SHEHealthCareImplService", targetNamespace = "http://Sherbrooke.Server.RM3/", wsdlLocation = "file:/C:/Users/mauli/Desktop/MACS/COMP%206231%20-%20Distributed%20System%20Design/Assignments/COMP%206231%20-%20DAMS%20Project/src/RM3/Server/Sherbrooke/SHEServer.wsdl")
public class SHEHealthCareImplService
    extends Service
{

    private final static URL SHEHEALTHCAREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHEHEALTHCAREIMPLSERVICE_EXCEPTION;
    private final static QName SHEHEALTHCAREIMPLSERVICE_QNAME = new QName("http://Sherbrooke.Server.RM3/", "SHEHealthCareImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/mauli/Desktop/MACS/COMP%206231%20-%20Distributed%20System%20Design/Assignments/COMP%206231%20-%20DAMS%20Project/src/RM3/Server/Sherbrooke/SHEServer.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHEHEALTHCAREIMPLSERVICE_WSDL_LOCATION = url;
        SHEHEALTHCAREIMPLSERVICE_EXCEPTION = e;
    }

    public SHEHealthCareImplService() {
        super(__getWsdlLocation(), SHEHEALTHCAREIMPLSERVICE_QNAME);
    }

    public SHEHealthCareImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHEHEALTHCAREIMPLSERVICE_QNAME, features);
    }

    public SHEHealthCareImplService(URL wsdlLocation) {
        super(wsdlLocation, SHEHEALTHCAREIMPLSERVICE_QNAME);
    }

    public SHEHealthCareImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHEHEALTHCAREIMPLSERVICE_QNAME, features);
    }

    public SHEHealthCareImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SHEHealthCareImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SHEHealthCareImpl
     */
    @WebEndpoint(name = "SHEHealthCareImplPort")
    public SHEHealthCareImpl getSHEHealthCareImplPort() {
        return super.getPort(new QName("http://Sherbrooke.Server.RM3/", "SHEHealthCareImplPort"), SHEHealthCareImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SHEHealthCareImpl
     */
    @WebEndpoint(name = "SHEHealthCareImplPort")
    public SHEHealthCareImpl getSHEHealthCareImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Sherbrooke.Server.RM3/", "SHEHealthCareImplPort"), SHEHealthCareImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHEHEALTHCAREIMPLSERVICE_EXCEPTION!= null) {
            throw SHEHEALTHCAREIMPLSERVICE_EXCEPTION;
        }
        return SHEHEALTHCAREIMPLSERVICE_WSDL_LOCATION;
    }

}
